<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="5" failed="5" ignored="0" total="10" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="AKKU_Sanity" duration-ms="141592" started-at="2017-11-29T12:11:45Z" finished-at="2017-11-29T12:14:07Z">
    <groups>
    </groups>
    <test name="Login and logout in Chrome" duration-ms="141592" started-at="2017-11-29T12:11:45Z" finished-at="2017-11-29T12:14:07Z">
      <class name="com.app.akku.work.TestCases.AKKU_01_LoginANDlogout">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.app.akku.work.TestCases.AKKU_01_LoginANDlogout@35fc6dc4]" name="setUp" is-config="true" duration-ms="158" started-at="2017-11-29T17:41:45Z" finished-at="2017-11-29T17:41:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="setup(java.lang.String, java.lang.String)[pri:0, instance:com.app.akku.work.TestCases.AKKU_01_LoginANDlogout@35fc6dc4]" name="setup" is-config="true" duration-ms="7635" started-at="2017-11-29T17:41:45Z" finished-at="2017-11-29T17:41:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://pre-prod.akku.work/]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[W_chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="SKIP" signature="AK_01_ValidLogin(java.lang.String, java.lang.String)[pri:0, instance:com.app.akku.work.TestCases.AKKU_01_LoginANDlogout@35fc6dc4]" name="AK_01_ValidLogin" duration-ms="23340" started-at="2017-11-29T17:41:53Z" data-provider="Login_Details" finished-at="2017-11-29T17:42:16Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[qa@demo.cloudnowtech.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password1]]>
              </value>
            </param>
          </params>
          <exception class="testlink.api.java.client.TestLinkAPIException">
            <message>
              <![CDATA[The required parameter status was not provided by the caller.]]>
            </message>
            <full-stacktrace>
              <![CDATA[testlink.api.java.client.TestLinkAPIException: The required parameter status was not provided by the caller.
	at testlink.api.java.client.TestLinkAPIClient.setParam(TestLinkAPIClient.java:1310)
	at testlink.api.java.client.TestLinkAPIClient.reportTestCaseResult(TestLinkAPIClient.java:281)
	at testlink.api.java.client.TestLinkAPIClient.reportTestCaseResult(TestLinkAPIClient.java:246)
	at testlink.api.java.client.TestLinkAPIClient.reportTestCaseResult(TestLinkAPIClient.java:217)
	at com.app.akku.work.common.TestLinkIntegration.reportResult(TestLinkIntegration.java:16)
	at com.app.akku.work.TestCases.AKKU_01_LoginANDlogout.AK_01_ValidLogin(AKKU_01_LoginANDlogout.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- testlink.api.java.client.TestLinkAPIException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AK_01_ValidLogin -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.app.akku.work.TestCases.AKKU_01_LoginANDlogout@35fc6dc4]" name="tearDown" is-config="true" duration-ms="13" started-at="2017-11-29T17:42:16Z" finished-at="2017-11-29T17:42:16Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=AK_01_ValidLogin status=SKIP method=AKKU_01_LoginANDlogout.AK_01_ValidLogin(java.lang.String, java.lang.String)[pri:0, instance:com.app.akku.work.TestCases.AKKU_01_LoginANDlogout@35fc6dc4] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="FAIL" signature="AK_01_ValidLogin(java.lang.String, java.lang.String)[pri:0, instance:com.app.akku.work.TestCases.AKKU_01_LoginANDlogout@35fc6dc4]" name="AK_01_ValidLogin" duration-ms="22569" started-at="2017-11-29T17:42:17Z" data-provider="Login_Details" finished-at="2017-11-29T17:42:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[qa@demo.cloudnowtech.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password1]]>
              </value>
            </param>
          </params>
          <exception class="testlink.api.java.client.TestLinkAPIException">
            <message>
              <![CDATA[The required parameter status was not provided by the caller.]]>
            </message>
            <full-stacktrace>
              <![CDATA[testlink.api.java.client.TestLinkAPIException: The required parameter status was not provided by the caller.
	at testlink.api.java.client.TestLinkAPIClient.setParam(TestLinkAPIClient.java:1310)
	at testlink.api.java.client.TestLinkAPIClient.reportTestCaseResult(TestLinkAPIClient.java:281)
	at testlink.api.java.client.TestLinkAPIClient.reportTestCaseResult(TestLinkAPIClient.java:246)
	at testlink.api.java.client.TestLinkAPIClient.reportTestCaseResult(TestLinkAPIClient.java:217)
	at com.app.akku.work.common.TestLinkIntegration.reportResult(TestLinkIntegration.java:16)
	at com.app.akku.work.TestCases.AKKU_01_LoginANDlogout.AK_01_ValidLogin(AKKU_01_LoginANDlogout.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- testlink.api.java.client.TestLinkAPIException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AK_01_ValidLogin -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.app.akku.work.TestCases.AKKU_01_LoginANDlogout@35fc6dc4]" name="tearDown" is-config="true" duration-ms="464" started-at="2017-11-29T17:42:39Z" finished-at="2017-11-29T17:42:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=AK_01_ValidLogin status=FAILURE method=AKKU_01_LoginANDlogout.AK_01_ValidLogin(java.lang.String, java.lang.String)[pri:0, instance:com.app.akku.work.TestCases.AKKU_01_LoginANDlogout@35fc6dc4] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="SKIP" signature="AK_02_LoginWithValidEmailAndInvalidPassword(java.lang.String, java.lang.String)[pri:0, instance:com.app.akku.work.TestCases.AKKU_01_LoginANDlogout@35fc6dc4]" name="AK_02_LoginWithValidEmailAndInvalidPassword" duration-ms="10779" started-at="2017-11-29T17:42:40Z" data-provider="Invalid_LoginPwdDetails" finished-at="2017-11-29T17:42:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[qa@demo.cloudnowtech.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password987]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.fail(Assert.java:100)
	at com.app.akku.work.TestCases.AKKU_01_LoginANDlogout.AK_02_LoginWithValidEmailAndInvalidPassword(AKKU_01_LoginANDlogout.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AK_02_LoginWithValidEmailAndInvalidPassword -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.app.akku.work.TestCases.AKKU_01_LoginANDlogout@35fc6dc4]" name="tearDown" is-config="true" duration-ms="5" started-at="2017-11-29T17:42:51Z" finished-at="2017-11-29T17:42:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=AK_02_LoginWithValidEmailAndInvalidPassword status=SKIP method=AKKU_01_LoginANDlogout.AK_02_LoginWithValidEmailAndInvalidPassword(java.lang.String, java.lang.String)[pri:0, instance:com.app.akku.work.TestCases.AKKU_01_LoginANDlogout@35fc6dc4] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="FAIL" signature="AK_02_LoginWithValidEmailAndInvalidPassword(java.lang.String, java.lang.String)[pri:0, instance:com.app.akku.work.TestCases.AKKU_01_LoginANDlogout@35fc6dc4]" name="AK_02_LoginWithValidEmailAndInvalidPassword" duration-ms="10608" started-at="2017-11-29T17:42:51Z" data-provider="Invalid_LoginPwdDetails" finished-at="2017-11-29T17:43:01Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[qa@demo.cloudnowtech.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password987]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.fail(Assert.java:100)
	at com.app.akku.work.TestCases.AKKU_01_LoginANDlogout.AK_02_LoginWithValidEmailAndInvalidPassword(AKKU_01_LoginANDlogout.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AK_02_LoginWithValidEmailAndInvalidPassword -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.app.akku.work.TestCases.AKKU_01_LoginANDlogout@35fc6dc4]" name="tearDown" is-config="true" duration-ms="351" started-at="2017-11-29T17:43:01Z" finished-at="2017-11-29T17:43:02Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=AK_02_LoginWithValidEmailAndInvalidPassword status=FAILURE method=AKKU_01_LoginANDlogout.AK_02_LoginWithValidEmailAndInvalidPassword(java.lang.String, java.lang.String)[pri:0, instance:com.app.akku.work.TestCases.AKKU_01_LoginANDlogout@35fc6dc4] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="SKIP" signature="AK_03_LoginwithValidUserNameandEmptyPassword(java.lang.String, java.lang.String)[pri:0, instance:com.app.akku.work.TestCases.AKKU_01_LoginANDlogout@35fc6dc4]" name="AK_03_LoginwithValidUserNameandEmptyPassword" duration-ms="9069" started-at="2017-11-29T17:43:02Z" data-provider="Login_Details" finished-at="2017-11-29T17:43:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[qa@demo.cloudnowtech.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [com.aventstack.extentreports.ExtentTest@3ec11999] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [com.aventstack.extentreports.ExtentTest@3ec11999] but found []
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at com.app.akku.work.pageobjects.LoginPage.Loginpage.inputpassworderrormsgvalidation(Loginpage.java:41)
	at com.app.akku.work.TestCases.AKKU_01_LoginANDlogout.AK_03_LoginwithValidUserNameandEmptyPassword(AKKU_01_LoginANDlogout.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AK_03_LoginwithValidUserNameandEmptyPassword -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.app.akku.work.TestCases.AKKU_01_LoginANDlogout@35fc6dc4]" name="tearDown" is-config="true" duration-ms="5" started-at="2017-11-29T17:43:11Z" finished-at="2017-11-29T17:43:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=AK_03_LoginwithValidUserNameandEmptyPassword status=SKIP method=AKKU_01_LoginANDlogout.AK_03_LoginwithValidUserNameandEmptyPassword(java.lang.String, java.lang.String)[pri:0, instance:com.app.akku.work.TestCases.AKKU_01_LoginANDlogout@35fc6dc4] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="FAIL" signature="AK_03_LoginwithValidUserNameandEmptyPassword(java.lang.String, java.lang.String)[pri:0, instance:com.app.akku.work.TestCases.AKKU_01_LoginANDlogout@35fc6dc4]" name="AK_03_LoginwithValidUserNameandEmptyPassword" duration-ms="8904" started-at="2017-11-29T17:43:11Z" data-provider="Login_Details" finished-at="2017-11-29T17:43:20Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[qa@demo.cloudnowtech.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [com.aventstack.extentreports.ExtentTest@7555b920] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [com.aventstack.extentreports.ExtentTest@7555b920] but found []
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at com.app.akku.work.pageobjects.LoginPage.Loginpage.inputpassworderrormsgvalidation(Loginpage.java:41)
	at com.app.akku.work.TestCases.AKKU_01_LoginANDlogout.AK_03_LoginwithValidUserNameandEmptyPassword(AKKU_01_LoginANDlogout.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AK_03_LoginwithValidUserNameandEmptyPassword -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.app.akku.work.TestCases.AKKU_01_LoginANDlogout@35fc6dc4]" name="tearDown" is-config="true" duration-ms="349" started-at="2017-11-29T17:43:20Z" finished-at="2017-11-29T17:43:20Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=AK_03_LoginwithValidUserNameandEmptyPassword status=FAILURE method=AKKU_01_LoginANDlogout.AK_03_LoginwithValidUserNameandEmptyPassword(java.lang.String, java.lang.String)[pri:0, instance:com.app.akku.work.TestCases.AKKU_01_LoginANDlogout@35fc6dc4] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="SKIP" signature="AK_04_LoginwithinvalidUsernameandinvalidPassword(java.lang.String, java.lang.String)[pri:0, instance:com.app.akku.work.TestCases.AKKU_01_LoginANDlogout@35fc6dc4]" name="AK_04_LoginwithinvalidUsernameandinvalidPassword" duration-ms="11574" started-at="2017-11-29T17:43:20Z" data-provider="Invalid_LoginDetails" finished-at="2017-11-29T17:43:32Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[invalidEmail@demo.cloudnowtech.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Invalid Username Or Password] but found [Invalid E-Mail Address]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Invalid Username Or Password] but found [Invalid E-Mail Address]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.app.akku.work.pageobjects.LoginPage.Loginpage.EmailANDPwdErrorValidation(Loginpage.java:66)
	at com.app.akku.work.TestCases.AKKU_01_LoginANDlogout.AK_04_LoginwithinvalidUsernameandinvalidPassword(AKKU_01_LoginANDlogout.java:194)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AK_04_LoginwithinvalidUsernameandinvalidPassword -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.app.akku.work.TestCases.AKKU_01_LoginANDlogout@35fc6dc4]" name="tearDown" is-config="true" duration-ms="1" started-at="2017-11-29T17:43:32Z" finished-at="2017-11-29T17:43:32Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=AK_04_LoginwithinvalidUsernameandinvalidPassword status=SKIP method=AKKU_01_LoginANDlogout.AK_04_LoginwithinvalidUsernameandinvalidPassword(java.lang.String, java.lang.String)[pri:0, instance:com.app.akku.work.TestCases.AKKU_01_LoginANDlogout@35fc6dc4] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="FAIL" signature="AK_04_LoginwithinvalidUsernameandinvalidPassword(java.lang.String, java.lang.String)[pri:0, instance:com.app.akku.work.TestCases.AKKU_01_LoginANDlogout@35fc6dc4]" name="AK_04_LoginwithinvalidUsernameandinvalidPassword" duration-ms="10997" started-at="2017-11-29T17:43:32Z" data-provider="Invalid_LoginDetails" finished-at="2017-11-29T17:43:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[invalidEmail@demo.cloudnowtech.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Invalid Username Or Password] but found [Invalid E-Mail Address]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Invalid Username Or Password] but found [Invalid E-Mail Address]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.app.akku.work.pageobjects.LoginPage.Loginpage.EmailANDPwdErrorValidation(Loginpage.java:66)
	at com.app.akku.work.TestCases.AKKU_01_LoginANDlogout.AK_04_LoginwithinvalidUsernameandinvalidPassword(AKKU_01_LoginANDlogout.java:194)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AK_04_LoginwithinvalidUsernameandinvalidPassword -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.app.akku.work.TestCases.AKKU_01_LoginANDlogout@35fc6dc4]" name="tearDown" is-config="true" duration-ms="370" started-at="2017-11-29T17:43:43Z" finished-at="2017-11-29T17:43:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=AK_04_LoginwithinvalidUsernameandinvalidPassword status=FAILURE method=AKKU_01_LoginANDlogout.AK_04_LoginwithinvalidUsernameandinvalidPassword(java.lang.String, java.lang.String)[pri:0, instance:com.app.akku.work.TestCases.AKKU_01_LoginANDlogout@35fc6dc4] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="SKIP" signature="AK_05_LoginwithemptyUsernameandValidPassword(java.lang.String, java.lang.String)[pri:0, instance:com.app.akku.work.TestCases.AKKU_01_LoginANDlogout@35fc6dc4]" name="AK_05_LoginwithemptyUsernameandValidPassword" duration-ms="10843" started-at="2017-11-29T17:43:43Z" data-provider="Login_Details" finished-at="2017-11-29T17:43:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[qa@demo.cloudnowtech.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [com.aventstack.extentreports.ExtentTest@7e1a1da6] but found [A part following '@' should not contain the symbol '@'.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [com.aventstack.extentreports.ExtentTest@7e1a1da6] but found [A part following '@' should not contain the symbol '@'.]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at com.app.akku.work.pageobjects.LoginPage.Loginpage.inputemailerrormsgvalidation(Loginpage.java:50)
	at com.app.akku.work.TestCases.AKKU_01_LoginANDlogout.AK_05_LoginwithemptyUsernameandValidPassword(AKKU_01_LoginANDlogout.java:226)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AK_05_LoginwithemptyUsernameandValidPassword -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.app.akku.work.TestCases.AKKU_01_LoginANDlogout@35fc6dc4]" name="tearDown" is-config="true" duration-ms="1" started-at="2017-11-29T17:43:54Z" finished-at="2017-11-29T17:43:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=AK_05_LoginwithemptyUsernameandValidPassword status=SKIP method=AKKU_01_LoginANDlogout.AK_05_LoginwithemptyUsernameandValidPassword(java.lang.String, java.lang.String)[pri:0, instance:com.app.akku.work.TestCases.AKKU_01_LoginANDlogout@35fc6dc4] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="FAIL" signature="AK_05_LoginwithemptyUsernameandValidPassword(java.lang.String, java.lang.String)[pri:0, instance:com.app.akku.work.TestCases.AKKU_01_LoginANDlogout@35fc6dc4]" name="AK_05_LoginwithemptyUsernameandValidPassword" duration-ms="10659" started-at="2017-11-29T17:43:54Z" data-provider="Login_Details" finished-at="2017-11-29T17:44:05Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[qa@demo.cloudnowtech.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [com.aventstack.extentreports.ExtentTest@4b629f13] but found [A part following '@' should not contain the symbol '@'.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [com.aventstack.extentreports.ExtentTest@4b629f13] but found [A part following '@' should not contain the symbol '@'.]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at com.app.akku.work.pageobjects.LoginPage.Loginpage.inputemailerrormsgvalidation(Loginpage.java:50)
	at com.app.akku.work.TestCases.AKKU_01_LoginANDlogout.AK_05_LoginwithemptyUsernameandValidPassword(AKKU_01_LoginANDlogout.java:226)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AK_05_LoginwithemptyUsernameandValidPassword -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.app.akku.work.TestCases.AKKU_01_LoginANDlogout@35fc6dc4]" name="tearDown" is-config="true" duration-ms="335" started-at="2017-11-29T17:44:05Z" finished-at="2017-11-29T17:44:05Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=AK_05_LoginwithemptyUsernameandValidPassword status=FAILURE method=AKKU_01_LoginANDlogout.AK_05_LoginwithemptyUsernameandValidPassword(java.lang.String, java.lang.String)[pri:0, instance:com.app.akku.work.TestCases.AKKU_01_LoginANDlogout@35fc6dc4] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.app.akku.work.TestCases.AKKU_01_LoginANDlogout@35fc6dc4]" name="teardown" is-config="true" duration-ms="1232" started-at="2017-11-29T17:44:05Z" finished-at="2017-11-29T17:44:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.app.akku.work.TestCases.AKKU_01_LoginANDlogout -->
    </test> <!-- Login and logout in Chrome -->
  </suite> <!-- AKKU_Sanity -->
</testng-results>
