<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="CN-D-027" name="com.app.akku.work.TestCases.AKKU_01_LoginANDlogout" tests="6" failures="1" timestamp="30 Nov 2017 04:48:49 GMT" time="83.920" errors="0">
  <testcase name="AK_04_LoginwithinvalidUsernameandinvalidPassword" time="11.090" classname="com.app.akku.work.TestCases.AKKU_01_LoginANDlogout">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.fail(Assert.java:100)
	at com.app.akku.work.TestCases.AKKU_01_LoginANDlogout.AK_04_LoginwithinvalidUsernameandinvalidPassword(AKKU_01_LoginANDlogout.java:222)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- AK_04_LoginwithinvalidUsernameandinvalidPassword -->
  <testcase name="AK_01_ValidLogin" time="26.827" classname="com.app.akku.work.TestCases.AKKU_01_LoginANDlogout"/>
  <testcase name="AK_03_LoginwithValidUserNameandEmptyPassword" time="10.173" classname="com.app.akku.work.TestCases.AKKU_01_LoginANDlogout"/>
  <testcase name="AK_02_LoginWithValidEmailAndInvalidPassword" time="11.140" classname="com.app.akku.work.TestCases.AKKU_01_LoginANDlogout"/>
  <testcase name="AK_04_LoginwithinvalidUsernameandinvalidPassword" time="14.095" classname="com.app.akku.work.TestCases.AKKU_01_LoginANDlogout">
    <skipped/>
  </testcase> <!-- AK_04_LoginwithinvalidUsernameandinvalidPassword -->
  <testcase name="AK_05_LoginwithemptyUsernameandValidPassword" time="10.595" classname="com.app.akku.work.TestCases.AKKU_01_LoginANDlogout"/>
</testsuite> <!-- com.app.akku.work.TestCases.AKKU_01_LoginANDlogout -->
